Map productDetails = {
  "id": 1383,
  "brand": {"name": "Rice", "image": "https://d1ojphegpburrh.cloudfront.net/media/brand_images/supplyline_logo.png", "header_image": null, "slug": "rice"},
  "image": "https://d1ojphegpburrh.cloudfront.net/media/images/product/None/1383/%E0%A6%B8%E0%A6%9C_4.png",
  "charge": {
    "booking_price": 0.0,
    "current_charge": 1880.0,
    "discount_charge": null,
    "selling_price": 2200.0,
    "profit": 320.0,
    "is_event": false,
    "event_id": null,
    "highlight": false,
    "highlight_id": null,
    "groupping": false,
    "groupping_id": null,
    "campaign_section_id": null,
    "campaign_section": false,
    "message": null
  },
  "images": [
    {"id": 1456, "image": "https://d1ojphegpburrh.cloudfront.net/media/images/product/None/1463/%E0%A6%9A%E0%A6%B2_16.png", "is_primary": true, "product": 1463},
    {"id": 1376, "image": "https://d1ojphegpburrh.cloudfront.net/media/images/product/None/1383/%E0%A6%B8%E0%A6%9C_4.png", "is_primary": true, "product": 1383}
  ],
  "slug": "-5s5b",
  "product_name": "মোজাম্মেল সিদ্ধ খুদ- ৫০ কেজি",
  "model": "",
  "commission_type": "Percent",
  "amount": "0.00",
  "tag": "",
  "description":
      "                                     <font color=\"#000000\" face=\"Noto Sans, sans-serif\" style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Noto Sans&quot;, sans-serif; font-size: 16px; letter-spacing: 0.14px;\"><span style=\"margin: 0px; padding: 0px; letter-spacing: -0.3px;\">প্রদর্শিত বিক্রয়মূল্য এবং লাভের পরিমাণ পরিবর্তনশীল। বাজার এবং&nbsp;</span></font><span style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Noto Sans&quot;, sans-serif; font-size: 16px; letter-spacing: -0.3px;\">বিক্রেতার</span><font color=\"#000000\" face=\"Noto Sans, sans-serif\" style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Noto Sans&quot;, sans-serif; font-size: 16px; letter-spacing: 0.14px;\"><span style=\"margin: 0px; padding: 0px; letter-spacing: -0.3px;\">&nbsp;বিবেচনার উপর নির্ভরশীল।</span></font>                                     ",
  "note": "                                                                                    ",
  "embadded_video_link": "                                          ",
  "maximum_order": 100,
  "stock": 848,
  "is_back_order": false,
  "specification": "<|>",
  "warranty": "                                                                                    ",
  "pre_order": false,
  "product_review": 5,
  "is_seller": false,
  "is_phone": false,
  "will_show_emi": false,
  "badge": null,
  "is_active": true,
  "created_at": "2021-09-23T17:17:37.852953+06:00",
  "updated_at": "2022-09-19T21:37:13.050814+06:00",
  "language": null,
  "seller": "SupplyLine",
  "combo": null,
  "created_by": "qtecsl",
  "updated_by": null,
  "category": [18],
  "related_product": [],
  "filter_value": []
};

List results = [
  {
    "id": 1383,
    "brand": {"name": "Rice", "image": "https://d1ojphegpburrh.cloudfront.net/media/brand_images/supplyline_logo.png", "header_image": null, "slug": "rice"},
    "image": "https://d1ojphegpburrh.cloudfront.net/media/images/product/None/1383/%E0%A6%B8%E0%A6%9C_4.png",
    "charge": {
      "booking_price": 0.0,
      "current_charge": 1880.0,
      "discount_charge": null,
      "selling_price": 2200.0,
      "profit": 320.0,
      "is_event": false,
      "event_id": null,
      "highlight": false,
      "highlight_id": null,
      "groupping": false,
      "groupping_id": null,
      "campaign_section_id": null,
      "campaign_section": false,
      "message": null
    },
    "images": [
      {"id": 1376, "image": "https://d1ojphegpburrh.cloudfront.net/media/images/product/None/1383/%E0%A6%B8%E0%A6%9C_4.png", "is_primary": true, "product": 1383}
    ],
    "slug": "-5s5b",
    "product_name": "মোজাম্মেল সিদ্ধ খুদ- ৫০ কেজি",
    "model": "",
    "commission_type": "Percent",
    "amount": "0.00",
    "tag": "",
    "description":
        "                                     <font color=\"#000000\" face=\"Noto Sans, sans-serif\" style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Noto Sans&quot;, sans-serif; font-size: 16px; letter-spacing: 0.14px;\"><span style=\"margin: 0px; padding: 0px; letter-spacing: -0.3px;\">প্রদর্শিত বিক্রয়মূল্য এবং লাভের পরিমাণ পরিবর্তনশীল। বাজার এবং&nbsp;</span></font><span style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Noto Sans&quot;, sans-serif; font-size: 16px; letter-spacing: -0.3px;\">বিক্রেতার</span><font color=\"#000000\" face=\"Noto Sans, sans-serif\" style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Noto Sans&quot;, sans-serif; font-size: 16px; letter-spacing: 0.14px;\"><span style=\"margin: 0px; padding: 0px; letter-spacing: -0.3px;\">&nbsp;বিবেচনার উপর নির্ভরশীল।</span></font>                                     ",
    "note": "                                                                                    ",
    "embadded_video_link": "                                          ",
    "maximum_order": 100,
    "stock": 848,
    "is_back_order": false,
    "specification": "<|>",
    "warranty": "                                                                                    ",
    "pre_order": false,
    "product_review": 5,
    "is_seller": false,
    "is_phone": false,
    "will_show_emi": false,
    "badge": null,
    "is_active": true,
    "created_at": "2021-09-23T17:17:37.852953+06:00",
    "updated_at": "2022-09-19T21:37:13.050814+06:00",
    "language": null,
    "seller": "SupplyLine",
    "combo": null,
    "created_by": "qtecsl",
    "updated_by": null,
    "category": [18],
    "related_product": [],
    "filter_value": []
  },
  {
    "id": 1384,
    "brand": {"name": "Rice", "image": "https://d1ojphegpburrh.cloudfront.net/media/brand_images/supplyline_logo.png", "header_image": null, "slug": "rice"},
    "image": "https://d1ojphegpburrh.cloudfront.net/media/images/product/None/1384/%E0%A6%B8%E0%A6%9C_5.png",
    "charge": {
      "booking_price": 0.0,
      "current_charge": 1630.0,
      "discount_charge": null,
      "selling_price": 1800.0,
      "profit": 170.0,
      "is_event": false,
      "event_id": null,
      "highlight": false,
      "highlight_id": null,
      "groupping": false,
      "groupping_id": null,
      "campaign_section_id": null,
      "campaign_section": false,
      "message": null
    },
    "images": [
      {"id": 1377, "image": "https://d1ojphegpburrh.cloudfront.net/media/images/product/None/1384/%E0%A6%B8%E0%A6%9C_5.png", "is_primary": true, "product": 1384}
    ],
    "slug": "-0vl5",
    "product_name": "পালকি নাজিরশাইল চাল (সবুজ)- ২৫ কেজি",
    "model": "",
    "commission_type": "Percent",
    "amount": "0.00",
    "tag": "",
    "description":
        "                                                  <font color=\"#000000\" face=\"Noto Sans, sans-serif\" style=\"letter-spacing: 0.14px;\"><span style=\"font-size: 16px; letter-spacing: -0.3px;\">প্রদর্শিত বিক্রয়মূল্য এবং লাভের পরিমাণ পরিবর্তনশীল। বাজার এবং&nbsp;</span></font><span style=\"color: rgb(0, 0, 0); font-family: &quot;Noto Sans&quot;, sans-serif; font-size: 16px; letter-spacing: -0.3px;\">বিক্রেতার</span><font color=\"#000000\" face=\"Noto Sans, sans-serif\" style=\"letter-spacing: 0.14px;\"><span style=\"font-size: 16px; letter-spacing: -0.3px;\">&nbsp;বিবেচনার উপর নির্ভরশীল।</span></font>                                                  ",
    "note": "                                                                                                            ",
    "embadded_video_link": "                                                      ",
    "maximum_order": 100,
    "stock": 171,
    "is_back_order": false,
    "specification": "<|>",
    "warranty": "                                                                                                            ",
    "pre_order": false,
    "product_review": 5,
    "is_seller": false,
    "is_phone": false,
    "will_show_emi": false,
    "badge": null,
    "is_active": true,
    "created_at": "2021-09-23T17:32:20.383611+06:00",
    "updated_at": "2022-09-26T12:32:12.017857+06:00",
    "language": null,
    "seller": "SupplyLine",
    "combo": null,
    "created_by": "qtecsl",
    "updated_by": null,
    "category": [31, 18],
    "related_product": [],
    "filter_value": []
  },
  {
    "id": 1388,
    "brand": {"name": "Rice", "image": "https://d1ojphegpburrh.cloudfront.net/media/brand_images/supplyline_logo.png", "header_image": null, "slug": "rice"},
    "image": "https://d1ojphegpburrh.cloudfront.net/media/images/product/None/1388/%E0%A6%B8%E0%A6%9C_9.png",
    "charge": {
      "booking_price": 0.0,
      "current_charge": 2670.0,
      "discount_charge": null,
      "selling_price": 2800.0,
      "profit": 130.0,
      "is_event": false,
      "event_id": null,
      "highlight": false,
      "highlight_id": null,
      "groupping": false,
      "groupping_id": null,
      "campaign_section_id": null,
      "campaign_section": false,
      "message": null
    },
    "images": [
      {"id": 1381, "image": "https://d1ojphegpburrh.cloudfront.net/media/images/product/None/1388/%E0%A6%B8%E0%A6%9C_9.png", "is_primary": true, "product": 1388}
    ],
    "slug": "-exxa",
    "product_name": "জোড়া ইলিশ বিরুই চাল- ৫০ কেজি",
    "model": "",
    "commission_type": "Percent",
    "amount": "0.00",
    "tag": "",
    "description":
        "                                      <span style=\"letter-spacing: 0.14px;\">Special Miniket Rice is parboiled rice, quite famous and staple rice of Bengal. It is white and extra-long and has a beautiful, subtle aroma. It is acknowledged for properties like high nutrition value, extra-long grains and is simple to digest. Serve it hot with a selected choice of daal with a dash of pure ghee and Jhuri alu bhaja/assorted papads.</span>                                         ",
    "note": "                                                                              ",
    "embadded_video_link": "                                       ",
    "maximum_order": 100,
    "stock": 18,
    "is_back_order": false,
    "specification": "<|>",
    "warranty": "                                                                              ",
    "pre_order": false,
    "product_review": 5,
    "is_seller": false,
    "is_phone": false,
    "will_show_emi": false,
    "badge": null,
    "is_active": true,
    "created_at": "2021-09-27T13:05:41.516329+06:00",
    "updated_at": "2022-09-26T15:20:19.133133+06:00",
    "language": null,
    "seller": "SupplyLine",
    "combo": null,
    "created_by": "qtecsl",
    "updated_by": null,
    "category": [18],
    "related_product": [],
    "filter_value": []
  },
  {
    "id": 1418,
    "brand": {"name": "Rice", "image": "https://d1ojphegpburrh.cloudfront.net/media/brand_images/supplyline_logo.png", "header_image": null, "slug": "rice"},
    "image": "https://d1ojphegpburrh.cloudfront.net/media/images/product/None/1418/%E0%A7%A8_%E0%A6%95%E0%A6%9C_7.png",
    "charge": {
      "booking_price": 0.0,
      "current_charge": 2860.0,
      "discount_charge": null,
      "selling_price": 3500.0,
      "profit": 640.0,
      "is_event": false,
      "event_id": null,
      "highlight": false,
      "highlight_id": null,
      "groupping": false,
      "groupping_id": null,
      "campaign_section_id": null,
      "campaign_section": false,
      "message": null
    },
    "images": [
      {"id": 1411, "image": "https://d1ojphegpburrh.cloudfront.net/media/images/product/None/1418/%E0%A7%A8_%E0%A6%95%E0%A6%9C_7.png", "is_primary": true, "product": 1418}
    ],
    "slug": "-c0jf",
    "product_name": "খাদিম সুপার চিনিগুড়া- ২৫ কেজি",
    "model": "",
    "commission_type": "Percent",
    "amount": "0.00",
    "tag": "",
    "description":
        "                                                            <font color=\"#000000\" face=\"Noto Sans, sans-serif\" style=\"letter-spacing: 0.14px;\"><span style=\"font-size: 16px; letter-spacing: -0.3px;\">প্রদর্শিত বিক্রয়মূল্য এবং লাভের পরিমাণ পরিবর্তনশীল। বাজার এবং&nbsp;</span></font><span style=\"color: rgb(0, 0, 0); font-family: &quot;Noto Sans&quot;, sans-serif; font-size: 16px; letter-spacing: -0.3px;\">বিক্রেতার</span><font color=\"#000000\" face=\"Noto Sans, sans-serif\" style=\"letter-spacing: 0.14px;\"><span style=\"font-size: 16px; letter-spacing: -0.3px;\">&nbsp;বিবেচনার উপর নির্ভরশীল।</span></font>                                                            ",
    "note": "                                                                                                                          ",
    "embadded_video_link": "                                                             ",
    "maximum_order": 100,
    "stock": 28,
    "is_back_order": false,
    "specification": "<|>",
    "warranty": "                                                                                                                          ",
    "pre_order": false,
    "product_review": 5,
    "is_seller": false,
    "is_phone": false,
    "will_show_emi": false,
    "badge": null,
    "is_active": true,
    "created_at": "2021-11-03T13:23:07.996991+06:00",
    "updated_at": "2022-09-26T15:18:12.827982+06:00",
    "language": null,
    "seller": "SupplyLine",
    "combo": null,
    "created_by": "qtecsl",
    "updated_by": null,
    "category": [18],
    "related_product": [],
    "filter_value": []
  },
  {
    "id": 1419,
    "brand": {"name": "Rice", "image": "https://d1ojphegpburrh.cloudfront.net/media/brand_images/supplyline_logo.png", "header_image": null, "slug": "rice"},
    "image": "https://d1ojphegpburrh.cloudfront.net/media/images/product/None/1419/%E0%A7%A8%E0%A7%AB_%E0%A6%95%E0%A6%9C_5.png",
    "charge": {
      "booking_price": 0.0,
      "current_charge": 2170.0,
      "discount_charge": null,
      "selling_price": 2500.0,
      "profit": 330.0,
      "is_event": false,
      "event_id": null,
      "highlight": false,
      "highlight_id": null,
      "groupping": false,
      "groupping_id": null,
      "campaign_section_id": null,
      "campaign_section": false,
      "message": null
    },
    "images": [
      {"id": 1412, "image": "https://d1ojphegpburrh.cloudfront.net/media/images/product/None/1419/%E0%A7%A8%E0%A7%AB_%E0%A6%95%E0%A6%9C_5.png", "is_primary": true, "product": 1419}
    ],
    "slug": "-aeh1",
    "product_name": "রানা স্পেশাল স্টিম কাটারী নাজিরশাইল চাল- ২৫ কেজি",
    "model": "",
    "commission_type": "Percent",
    "amount": "0.00",
    "tag": "",
    "description":
        "                                      <font color=\"#000000\" face=\"Noto Sans, sans-serif\" style=\"letter-spacing: 0.14px;\"><span style=\"font-size: 16px; letter-spacing: -0.3px;\">প্রদর্শিত বিক্রয়মূল্য এবং লাভের পরিমাণ পরিবর্তনশীল। বাজার এবং&nbsp;</span></font><span style=\"color: rgb(0, 0, 0); font-family: &quot;Noto Sans&quot;, sans-serif; font-size: 16px; letter-spacing: -0.3px;\">বিক্রেতার</span><font color=\"#000000\" face=\"Noto Sans, sans-serif\" style=\"letter-spacing: 0.14px;\"><span style=\"font-size: 16px; letter-spacing: -0.3px;\">&nbsp;বিবেচনার উপর নির্ভরশীল।</span></font>                                      ",
    "note": "                                                                                ",
    "embadded_video_link": "                                        ",
    "maximum_order": 100,
    "stock": 76,
    "is_back_order": false,
    "specification": "<|>",
    "warranty": "                                                                                ",
    "pre_order": false,
    "product_review": 5,
    "is_seller": false,
    "is_phone": false,
    "will_show_emi": false,
    "badge": null,
    "is_active": true,
    "created_at": "2021-11-03T13:26:40.350751+06:00",
    "updated_at": "2022-09-24T18:03:15.972747+06:00",
    "language": null,
    "seller": "SupplyLine",
    "combo": null,
    "created_by": "qtecsl",
    "updated_by": null,
    "category": [18],
    "related_product": [],
    "filter_value": []
  },
  {
    "id": 1430,
    "brand": {"name": "Rice", "image": "https://d1ojphegpburrh.cloudfront.net/media/brand_images/supplyline_logo.png", "header_image": null, "slug": "rice"},
    "image": "https://d1ojphegpburrh.cloudfront.net/media/images/product/None/1430/%E0%A6%9A%E0%A6%B2_1.png",
    "charge": {
      "booking_price": 0.0,
      "current_charge": 2640.0,
      "discount_charge": null,
      "selling_price": 2850.0,
      "profit": 210.0,
      "is_event": false,
      "event_id": null,
      "highlight": false,
      "highlight_id": null,
      "groupping": false,
      "groupping_id": null,
      "campaign_section_id": null,
      "campaign_section": false,
      "message": null
    },
    "images": [
      {"id": 1423, "image": "https://d1ojphegpburrh.cloudfront.net/media/images/product/None/1430/%E0%A6%9A%E0%A6%B2_1.png", "is_primary": true, "product": 1430}
    ],
    "slug": "-gbo2",
    "product_name": "জামাল স্পেশাল আটাশ ৫০ কেজি",
    "model": "",
    "commission_type": "Percent",
    "amount": "0.00",
    "tag": "",
    "description":
        "                                                                                                <p><span style=\"color: rgb(94, 88, 115); font-size: 11.998px; letter-spacing: 0.14px; text-align: right;\">Description:</span></p><p> </p><ul style=\"list-style: none; padding: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; color: rgb(102, 102, 102); font-family: &quot;Work Sans&quot;, Arial, sans-serif; font-size: 15px; letter-spacing: normal;\"><li style=\"margin-bottom: 7px; position: relative; padding-left: 15px;\"><font color=\"#000000\" face=\"Noto Sans, sans-serif\" style=\"font-size: 14px; letter-spacing: 0.14px;\"><span style=\"font-size: 16px; letter-spacing: -0.3px;\">প্রদর্শিত বিক্রয়মূল্য এবং লাভের পরিমাণ পরিবর্তনশীল। বাজার এবং&nbsp;</span></font><span style=\"color: rgb(0, 0, 0); font-family: &quot;Noto Sans&quot;, sans-serif; font-size: 16px; letter-spacing: -0.3px;\">বিক্রেতার</span><font color=\"#000000\" face=\"Noto Sans, sans-serif\" style=\"font-size: 14px; letter-spacing: 0.14px;\"><span style=\"font-size: 16px; letter-spacing: -0.3px;\">&nbsp;বিবেচনার উপর নির্ভরশীল।</span></font><br></li></ul>                                                                                                ",
    "note":
        "                                                                                                                                                                                                ",
    "embadded_video_link": "                                                                                                ",
    "maximum_order": 100,
    "stock": 54,
    "is_back_order": false,
    "specification": "<|>",
    "warranty":
        "                                                                                                                                                                                                ",
    "pre_order": false,
    "product_review": 5,
    "is_seller": false,
    "is_phone": false,
    "will_show_emi": false,
    "badge": null,
    "is_active": true,
    "created_at": "2021-11-17T15:22:47.262602+06:00",
    "updated_at": "2022-09-26T14:23:29.437739+06:00",
    "language": null,
    "seller": "SupplyLine",
    "combo": null,
    "created_by": "qtecsl",
    "updated_by": null,
    "category": [18],
    "related_product": [],
    "filter_value": []
  },
  {
    "id": 1433,
    "brand": {"name": "Rice", "image": "https://d1ojphegpburrh.cloudfront.net/media/brand_images/supplyline_logo.png", "header_image": null, "slug": "rice"},
    "image": "https://d1ojphegpburrh.cloudfront.net/media/images/product/None/1433/Add_a_heading_2.png",
    "charge": {
      "booking_price": 0.0,
      "current_charge": 3685.0,
      "discount_charge": null,
      "selling_price": 3800.0,
      "profit": 115.0,
      "is_event": false,
      "event_id": null,
      "highlight": false,
      "highlight_id": null,
      "groupping": false,
      "groupping_id": null,
      "campaign_section_id": null,
      "campaign_section": false,
      "message": null
    },
    "images": [
      {"id": 1426, "image": "https://d1ojphegpburrh.cloudfront.net/media/images/product/None/1433/Add_a_heading_2.png", "is_primary": true, "product": 1433}
    ],
    "slug": "-ruwc",
    "product_name": "বুশরা মিনিকেট- ৫০ কেজি",
    "model": "",
    "commission_type": "Percent",
    "amount": "0.00",
    "tag": "",
    "description":
        "                    <font color=\"#000000\" face=\"Noto Sans, sans-serif\" style=\"letter-spacing: 0.14px;\"><span style=\"font-size: 16px; letter-spacing: -0.3px;\">প্রদর্শিত বিক্রয়মূল্য এবং লাভের পরিমাণ পরিবর্তনশীল। বাজার এবং&nbsp;</span></font><span style=\"color: rgb(0, 0, 0); font-family: &quot;Noto Sans&quot;, sans-serif; font-size: 16px; letter-spacing: -0.3px;\">বিক্রেতার</span><font color=\"#000000\" face=\"Noto Sans, sans-serif\" style=\"letter-spacing: 0.14px;\"><span style=\"font-size: 16px; letter-spacing: -0.3px;\">&nbsp;বিবেচনার উপর নির্ভরশীল।&nbsp;</span></font>                    ",
    "note": "                                          ",
    "embadded_video_link": "                     ",
    "maximum_order": 100,
    "stock": 18,
    "is_back_order": false,
    "specification": "<|>",
    "warranty": "                                          ",
    "pre_order": false,
    "product_review": 5,
    "is_seller": false,
    "is_phone": false,
    "will_show_emi": false,
    "badge": null,
    "is_active": true,
    "created_at": "2021-11-17T15:57:03.895807+06:00",
    "updated_at": "2022-09-24T09:36:29.985540+06:00",
    "language": null,
    "seller": "SupplyLine",
    "combo": null,
    "created_by": "qtecsl",
    "updated_by": null,
    "category": [18],
    "related_product": [],
    "filter_value": []
  },
  {
    "id": 1455,
    "brand": {"name": "Rice", "image": "https://d1ojphegpburrh.cloudfront.net/media/brand_images/supplyline_logo.png", "header_image": null, "slug": "rice"},
    "image": "https://d1ojphegpburrh.cloudfront.net/media/images/product/None/1455/%E0%A6%9A%E0%A6%B2_11.png",
    "charge": {
      "booking_price": 0.0,
      "current_charge": 1720.0,
      "discount_charge": null,
      "selling_price": 1850.0,
      "profit": 130.0,
      "is_event": false,
      "event_id": null,
      "highlight": false,
      "highlight_id": null,
      "groupping": false,
      "groupping_id": null,
      "campaign_section_id": null,
      "campaign_section": false,
      "message": null
    },
    "images": [
      {"id": 1448, "image": "https://d1ojphegpburrh.cloudfront.net/media/images/product/None/1455/%E0%A6%9A%E0%A6%B2_11.png", "is_primary": true, "product": 1455}
    ],
    "slug": "-ujgi",
    "product_name": "ম্যাপকো কাটারী নাজিরশাইল- ২০ কেজি",
    "model": "",
    "commission_type": "Percent",
    "amount": "0.00",
    "tag": "",
    "description":
        "                             <font color=\"#000000\" face=\"Noto Sans, sans-serif\"><span style=\"font-size: 16px; letter-spacing: -0.3px;\">প্রদর্শিত বিক্রয়মূল্য এবং লাভের পরিমাণ পরিবর্তনশীল। বাজার এবং&nbsp;</span></font><span style=\"color: rgb(0, 0, 0); font-family: &quot;Noto Sans&quot;, sans-serif; font-size: 16px; letter-spacing: -0.3px;\">বিক্রেতার</span><font color=\"#000000\" face=\"Noto Sans, sans-serif\"><span style=\"font-size: 16px; letter-spacing: -0.3px;\">&nbsp;বিবেচনার উপর নির্ভরশীল।&nbsp;</span></font>                             ",
    "note": "                                                            ",
    "embadded_video_link": "                              ",
    "maximum_order": 100,
    "stock": 55,
    "is_back_order": false,
    "specification": "<|>",
    "warranty": "                                                            ",
    "pre_order": false,
    "product_review": 5,
    "is_seller": false,
    "is_phone": false,
    "will_show_emi": false,
    "badge": null,
    "is_active": true,
    "created_at": "2021-11-22T15:01:27.294519+06:00",
    "updated_at": "2022-09-25T17:18:52.939660+06:00",
    "language": null,
    "seller": "SupplyLine",
    "combo": null,
    "created_by": "qtecsl",
    "updated_by": null,
    "category": [18],
    "related_product": [],
    "filter_value": []
  },
  {
    "id": 1463,
    "brand": {"name": "Rice", "image": "https://d1ojphegpburrh.cloudfront.net/media/brand_images/supplyline_logo.png", "header_image": null, "slug": "rice"},
    "image": "https://d1ojphegpburrh.cloudfront.net/media/images/product/None/1463/%E0%A6%9A%E0%A6%B2_16.png",
    "charge": {
      "booking_price": 0.0,
      "current_charge": 2425.0,
      "discount_charge": null,
      "selling_price": 2600.0,
      "profit": 175.0,
      "is_event": false,
      "event_id": null,
      "highlight": false,
      "highlight_id": null,
      "groupping": false,
      "groupping_id": null,
      "campaign_section_id": null,
      "campaign_section": false,
      "message": null
    },
    "images": [
      {"id": 1456, "image": "https://d1ojphegpburrh.cloudfront.net/media/images/product/None/1463/%E0%A6%9A%E0%A6%B2_16.png", "is_primary": true, "product": 1463}
    ],
    "slug": "-kqdm",
    "product_name": "মোজাম্মেল বাসমতি- ২৫ কেজি",
    "model": "",
    "commission_type": "Percent",
    "amount": "0.00",
    "tag": "",
    "description":
        "            <font color=\"#000000\" face=\"Noto Sans, sans-serif\" style=\"letter-spacing: 0.14px;\"><span style=\"font-size: 16px; letter-spacing: -0.3px;\">প্রদর্শিত বিক্রয়মূল্য এবং লাভের পরিমাণ পরিবর্তনশীল। বাজার এবং&nbsp;</span></font><span style=\"color: rgb(0, 0, 0); font-family: &quot;Noto Sans&quot;, sans-serif; font-size: 16px; letter-spacing: -0.3px;\">বিক্রেতার</span><font color=\"#000000\" face=\"Noto Sans, sans-serif\" style=\"letter-spacing: 0.14px;\"><span style=\"font-size: 16px; letter-spacing: -0.3px;\">&nbsp;বিবেচনার উপর নির্ভরশীল।</span></font>             ",
    "note": "                        ",
    "embadded_video_link": "            ",
    "maximum_order": 100,
    "stock": 941,
    "is_back_order": false,
    "specification": "<|>",
    "warranty": "                        ",
    "pre_order": false,
    "product_review": 5,
    "is_seller": false,
    "is_phone": false,
    "will_show_emi": false,
    "badge": null,
    "is_active": true,
    "created_at": "2021-12-08T14:31:13.591277+06:00",
    "updated_at": "2022-09-25T17:52:05.116969+06:00",
    "language": null,
    "seller": "SupplyLine",
    "combo": null,
    "created_by": "qtecsl",
    "updated_by": null,
    "category": [18],
    "related_product": [],
    "filter_value": []
  },
  {
    "id": 1468,
    "brand": {"name": "Rice", "image": "https://d1ojphegpburrh.cloudfront.net/media/brand_images/supplyline_logo.png", "header_image": null, "slug": "rice"},
    "image": "https://d1ojphegpburrh.cloudfront.net/media/images/product/None/1468/%E0%A7%AB%E0%A7%A6_%E0%A6%95%E0%A6%9C_13.png",
    "charge": {
      "booking_price": 0.0,
      "current_charge": 6030.0,
      "discount_charge": null,
      "selling_price": 7000.0,
      "profit": 970.0,
      "is_event": false,
      "event_id": null,
      "highlight": false,
      "highlight_id": null,
      "groupping": false,
      "groupping_id": null,
      "campaign_section_id": null,
      "campaign_section": false,
      "message": null
    },
    "images": [
      {
        "id": 1461,
        "image": "https://d1ojphegpburrh.cloudfront.net/media/images/product/None/1468/%E0%A7%AB%E0%A7%A6_%E0%A6%95%E0%A6%9C_13.png",
        "is_primary": true,
        "product": 1468
      }
    ],
    "slug": "-lk0v",
    "product_name": "নজরুল চিনিগুড়া চাল-৫০ কেজি",
    "model": "",
    "commission_type": "Percent",
    "amount": "0.00",
    "tag": "",
    "description":
        "                                                       <font color=\"#000000\" face=\"Noto Sans, sans-serif\" style=\"letter-spacing: 0.14px;\"><span style=\"font-size: 16px; letter-spacing: -0.3px;\">প্রদর্শিত বিক্রয়মূল্য এবং লাভের পরিমাণ পরিবর্তনশীল। বাজার এবং&nbsp;</span></font><span style=\"color: rgb(0, 0, 0); font-family: &quot;Noto Sans&quot;, sans-serif; font-size: 16px; letter-spacing: -0.3px;\">বিক্রেতার</span><font color=\"#000000\" face=\"Noto Sans, sans-serif\" style=\"letter-spacing: 0.14px;\"><span style=\"font-size: 16px; letter-spacing: -0.3px;\">&nbsp;বিবেচনার উপর নির্ভরশীল।</span></font>                                                        ",
    "note": "                                                                                                              ",
    "embadded_video_link": "                                                       ",
    "maximum_order": 100,
    "stock": 0,
    "is_back_order": false,
    "specification": "<|>",
    "warranty": "                                                                                                              ",
    "pre_order": false,
    "product_review": 5,
    "is_seller": false,
    "is_phone": false,
    "will_show_emi": false,
    "badge": null,
    "is_active": true,
    "created_at": "2021-12-15T10:57:28.987079+06:00",
    "updated_at": "2022-09-24T11:58:47.908399+06:00",
    "language": null,
    "seller": "SupplyLine",
    "combo": null,
    "created_by": "qtecsl",
    "updated_by": null,
    "category": [18],
    "related_product": [],
    "filter_value": []
  }
];

Map abd = {
  'id': 46,
  'brand': {
    'name': 'Abul Khair Consumer Goods',
    'image': 'https://d1ojphegpburrh.cloudfront.net/media/brand_images/abul_Khair.png',
    'header_image': 'https://d1ojphegpburrh.cloudfront.net/media/brand_images/Untitled_design_1.png',
    'slug': 'abul-khair-consumer-goods',
  },
  'image': 'https://d1ojphegpburrh.cloudfront.net/media/images/product/None/46/seylon400g.png',
  'charge': {
    'booking_price': 0.0,
    'current_charge': 180.0,
    'discount_charge': null,
    'selling_price': null,
    'profit': null,
    'is_event': false,
    'event_id': null,
    'highlight': false,
    'highlight_id': null,
    'groupping': false,
    'groupping_id': null,
    'campaign_section_id': null,
    'campaign_section': false,
    'message': null
  },
  'images': [
    {'id': 39, 'image': 'https://d1ojphegpburrh.cloudfront.net/media/images/product/None/46/seylon400g.png', 'is_primary': true, 'product': 46}
  ],
  'slug': '-tbte',
  'product_name': 'সিলন চা ৪০০ গ্রাম',
  'model': 'Tea',
  'commission_type': 'Percent',
  'amount': 0.00,
  'tag': 'Tea',
  'description': '',
  'note': '<span style="letter-spacing: 0.14px;">tea</span>',
  'embadded_video_link': '',
  'maximum_order': 100,
  'stock': 0,
  'is_back_order': false,
  'specification': '<|>',
  'warranty': '',
  'pre_order': false,
  'product_review': 5,
  'is_seller': false,
  'is_phone': false,
  'will_show_emi': false,
  'badge': null,
  'is_active': true,
  'created_at': '2021-07-08T18:04:17.998683+06:00',
  'updated_at': '2022-07-18T18:00:20.372306+06:00',
  'language': null,
  'seller': 'AKCG',
  'combo': null,
  'created_by': 'qtecsl',
  'updated_by': null,
  'category': [8],
  'related_product': [],
  'filter_value': []
};
