name: flutter_task
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-120.0.dev <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_html: ^2.2.1
  get: ^4.6.5
  hive_flutter: ^1.1.0
  http: ^0.13.5
  shimmer: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/image/
  fonts:
    - family: Baloo Da 2
      fonts:
        - asset: assets/fonts/Baloo_Da_2/BalooDa2-Medium.ttf
        - asset: assets/fonts/Baloo_Da_2/BalooDa2-Regular.ttf
        - asset: assets/fonts/Baloo_Da_2/BalooDa2-SemiBold.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
